DROP TABLE VIAJE CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS;
DROP TABLE VEHICULO CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_CONDUCTOR;
DROP SEQUENCE SEQ_VEHICULO;
DROP SEQUENCE SEQ_VIAJE;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMERIC(10) NOT NULL,
    RUT_CLIENTE VARCHAR2(80) NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(80) NOT NULL,
    DIRECCION_CLIENTE VARCHAR2(80) NOT NULL,
    EDAD_CLIENTE NUMERIC(3) NOT NULL,
    GENERO_CLIENTE VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CONDUCTOR (
    ID_CONDUCTOR NUMERIC(10) NOT NULL,
    RUT_CONDUCTOR VARCHAR2(80) NOT NULL,
    NOMBRE_CONDUCTOR VARCHAR2(80) NOT NULL,
    DIRECCION_CONDUCTOR VARCHAR2(80) NOT NULL,
    EDAD_CONDUCTOR NUMERIC(3) NOT NULL,
    GENERO_CONDUCTOR VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_CONDUCTOR PRIMARY KEY (ID_CONDUCTOR)
);

CREATE TABLE VEHICULO (
    ID_VEHICULO NUMERIC(10) NOT NULL,
    CHASIS_VEHICULO VARCHAR2(80) NOT NULL,
    PATENTE_VEHICULO VARCHAR2(80) NOT NULL,
    ANO_FABRICACION_VEHICULO NUMERIC(4) NOT NULL,
    MARCA_VEHICULO VARCHAR2(80) NOT NULL,
    MODELO_VEHICULO VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_VEHICULO PRIMARY KEY (ID_VEHICULO)
);

CREATE TABLE VIAJE(
    ID_VIAJE NUMERIC(10) NOT NULL,
    ID_CONDUCTOR NUMERIC(10) NOT NULL,
    ID_CLIENTE NUMERIC(10) NOT NULL,
    ID_VEHICULO NUMERIC(10) NOT NULL,
    DIRECCION_INICIO VARCHAR2(80) NOT NULL,
    DIRECCION_DESTINO VARCHAR2(80) NOT NULL,
    IDA_Y_VUELTA CHAR,
    FECHA_VIAJE DATE,   
    CONSTRAINT PK_VIAJE PRIMARY KEY (ID_VIAJE),
    CONSTRAINT FK_VIAJE_CONDUCTOR FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTOR(ID_CONDUCTOR),
    CONSTRAINT FK_VIAJE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_VIAJE_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO)
);

CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
;

CREATE SEQUENCE SEQ_CONDUCTOR
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
;

CREATE SEQUENCE SEQ_VEHICULO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
;

CREATE SEQUENCE SEQ_VIAJE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
;

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'9999999999','JUAN PEREZ','AVENIDA SIMIO 73',25,'Masculino');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'8888888888','ANA MENDOZA','AVENIDA SIMIO 75',24,'Femenino');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'7777777777','JOSE MARIA SOTO','AVENIDA SIMIO 75',24,'Otro');

INSERT INTO CONDUCTOR VALUES (SEQ_CONDUCTOR.NEXTVAL,'6666666666','JOSE FERNANDEZ','AVENIDA MONO 73',30,'Masculino');
INSERT INTO CONDUCTOR VALUES (SEQ_CONDUCTOR.NEXTVAL,'5555555555','SOFIA VERGARA','AVENIDA MONO 75',28,'Femenino');
INSERT INTO CONDUCTOR VALUES (SEQ_CONDUCTOR.NEXTVAL,'4444444444','ANTONIETO QUIROZ','AVENIDA MONO 80',31,'Otro');

INSERT INTO VEHICULO VALUES (SEQ_VEHICULO.NEXTVAL,'11Q2W3E4R5T','WRSF24',2014,'Toyota','Yaris');
INSERT INTO VEHICULO VALUES (SEQ_VEHICULO.NEXTVAL,'2W3E4R5T6Y','RTFG45',2019,'Nissan','vesta');
INSERT INTO VEHICULO VALUES (SEQ_VEHICULO.NEXTVAL,'3E4R5T6Y7U','TYGH56',2022,'Chevrolet','Astra');

INSERT INTO VIAJE VALUES(SEQ_VIAJE.NEXTVAL,1,1,1,'AVENIDA SIMIO 34', 'AVENIDA MONO 45', 'S', '27/11/2022');
INSERT INTO VIAJE VALUES(SEQ_VIAJE.NEXTVAL,2,2,2,'AVENIDA SIMIO 25', 'AVENIDA MONO 23', 'S', '27/11/2022');
INSERT INTO VIAJE VALUES(SEQ_VIAJE.NEXTVAL,3,3,3,'AVENIDA SIMIO 78', 'AVENIDA MONO 98', 'N', '27/11/2022');

commit;