
package Vista;

import Controlador.DaoConductor;
import Controlador.DaoUsuario;
import Controlador.DaoVehiculo;
import Controlador.DaoViaje;
import Modelo.Conductor;
import Modelo.Usuario;
import Modelo.Vehiculo;
import Modelo.Viaje;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class JFrmViaje extends javax.swing.JFrame {

    /**
     * Creates new form JFrmUsuario
     */
    public JFrmViaje() {
        initComponents();
        Listar();
        LlenarUsuario();
        Llenarconductor();
        LlenarVehiculo();
        LlenarVehiculoFiltro();
        Date fecha=new Date();
        JdcFechaDeViaje.setDate(fecha);
        setLocationRelativeTo(null);
    }

    private void LlenarUsuario() {
        cboRutUsuario.addItem("Seleccione");
        for (Usuario user : new DaoUsuario().Listar()) {
            cboRutUsuario.addItem(user.getRut());
            txtNombreUsuario.setText(user.getNombre());
            
        }
    }

    private void Llenarconductor() {
        cboRutConductor.addItem("Seleccione");
        for (Conductor cond : new DaoConductor().ListarConductor()) {
            cboRutConductor.addItem(cond.getRut());
            txtNombreConductor.setText(cond.getNombre());
            
        }
    }

    private void LlenarVehiculo() {
        cboVehiculo.addItem("Seleccione");
        for (Vehiculo vehi : new DaoVehiculo().Listar()) {
            cboVehiculo.addItem(vehi.getChasisVehiculo());
            
        }
    }
    
    
    private void LlenarVehiculoFiltro() {
        cboVehiculo.addItem("Seleccione");
        for (Vehiculo vehi : new DaoVehiculo().Listar()) {
            cboFiltroPatente.addItem(vehi.getPatenteVehiculo());
        }
    }
    
    private void Listar() {
        DefaultTableModel modelo=new DefaultTableModel();
        JTblListarViajes.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Conductor");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Inicio");
        modelo.addColumn("Fin");
        modelo.addColumn("IdaVuelta");
        modelo.addColumn("Fecha");
        ArrayList<Viaje> listado=new DaoViaje().Listar();
        for (Viaje item : listado) {
            Object[] fila=new Object[8];
            fila[0]=item.getId_viaje();
            fila[1]=item.getUsuario().getNombre();
            fila[2]=item.getConductor().getNombre();
            fila[3]=item.getVehiculo().getPatenteVehiculo();
            fila[4]=item.getDireccionInicio();
            fila[5]=item.getDireccionDestino();
            fila[6]=item.isIdaYVuelta()?"Si":"No";
            fila[7]=item.getFechaDeViaje();
            modelo.addRow(fila);
        }
    }

    
    public void ListarFiltroPatente(){
        DefaultTableModel modelo = new DefaultTableModel();
        JTblListarViajes.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Conductor");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Inicio");
        modelo.addColumn("Fin");
        modelo.addColumn("IdaVuelta");
        modelo.addColumn("Fecha");
        ArrayList<Viaje> Listado = new DaoViaje().Listar();
        String pat = cboFiltroPatente.getSelectedItem().toString();
        for (Viaje item: Listado) {
            if(item.getVehiculo().getPatenteVehiculo().equals(pat)){
            Object[] fila=new Object[8];
            fila[0]=item.getId_viaje();
            fila[1]=item.getUsuario().getNombre();
            fila[2]=item.getConductor().getNombre();
            fila[3]=item.getVehiculo().getPatenteVehiculo();
            fila[4]=item.getDireccionInicio();
            fila[5]=item.getDireccionDestino();
            fila[6]=item.isIdaYVuelta()?"S":"N";
            fila[7]=item.getFechaDeViaje().getTime();
            modelo.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionInicio = new javax.swing.JTextField();
        cboFiltroPatente = new javax.swing.JComboBox<>();
        btnFiltrarPatente = new javax.swing.JButton();
        btnListarFecha = new javax.swing.JButton();
        txtDireccionDestino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboRutConductor = new javax.swing.JComboBox<>();
        txtNombreConductor = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        cboRutUsuario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboVehiculo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RdBtnSi = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        RdBtnNo = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JdcFechaDeViaje = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdViaje = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblIdConductor = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblListarViajes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVolverMenuViaje = new javax.swing.JMenuItem();
        CerrarSesionViaje = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCerrarPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Viaje");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Rut Conductor");

        jLabel2.setText("Nombre Conductor");

        jLabel3.setText("Direccion Inicio");

        txtDireccionInicio.setMaximumSize(new java.awt.Dimension(200, 22));
        txtDireccionInicio.setMinimumSize(new java.awt.Dimension(200, 22));
        txtDireccionInicio.setPreferredSize(new java.awt.Dimension(200, 22));

        btnFiltrarPatente.setText("Filtrar");
        btnFiltrarPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarPatenteActionPerformed(evt);
            }
        });

        btnListarFecha.setText("Listar");
        btnListarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFechaActionPerformed(evt);
            }
        });

        txtDireccionDestino.setMaximumSize(new java.awt.Dimension(200, 22));
        txtDireccionDestino.setMinimumSize(new java.awt.Dimension(200, 22));
        txtDireccionDestino.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabel6.setText("Direccion Destino");

        cboRutConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutConductorActionPerformed(evt);
            }
        });

        txtNombreConductor.setEditable(false);
        txtNombreConductor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreConductor.setEnabled(false);

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreUsuario.setEnabled(false);

        cboRutUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Pasajero");

        jLabel5.setText("Rut Pasajero");

        cboVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVehiculoActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione Vehiculo");

        buttonGroup1.add(RdBtnSi);
        RdBtnSi.setText("SI");
        RdBtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnSiActionPerformed(evt);
            }
        });

        jLabel8.setText("Viaje de Ida y Vuelta");

        buttonGroup1.add(RdBtnNo);
        RdBtnNo.setText("NO");
        RdBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnNoActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel9.setText("Filtro por Patente");

        jLabel10.setText("Fecha de Viaje");

        jLabel11.setText("IdViaje");

        txtIdViaje.setEditable(false);
        txtIdViaje.setText("00");
        txtIdViaje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdViaje.setEnabled(false);
        txtIdViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdViajeActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblIdConductor.setText("00");
        lblIdConductor.setEnabled(false);

        lblIdCliente.setText("00");
        lblIdCliente.setEnabled(false);

        lblVehiculo.setText("00");
        lblVehiculo.setEnabled(false);

        JTblListarViajes.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JTblListarViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTblListarViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblListarViajesMouseClicked(evt);
            }
        });
        JTblListarViajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTblListarViajesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(JTblListarViajes);

        jMenu1.setText("File");

        mnuVolverMenuViaje.setText("Volver al Menu");
        mnuVolverMenuViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVolverMenuViajeActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVolverMenuViaje);

        CerrarSesionViaje.setText("Cerrar Sesion");
        CerrarSesionViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionViajeActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarSesionViaje);
        jMenu1.add(jSeparator1);

        mnuCerrarPrograma.setText("Cerrar Programa");
        mnuCerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarProgramaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCerrarPrograma);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboFiltroPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrarPatente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarFecha)
                                .addGap(106, 106, 106)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboRutConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RdBtnSi)
                                                .addGap(18, 18, 18)
                                                .addComponent(RdBtnNo))
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNombreConductor, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cboRutUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3)
                                                .addComponent(txtDireccionDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8)
                                                .addComponent(txtDireccionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JdcFechaDeViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboFiltroPatente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnListarFecha)
                                .addComponent(btnVolver)
                                .addComponent(btnFiltrarPatente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblIdConductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRutConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblIdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdBtnSi)
                            .addComponent(RdBtnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JdcFechaDeViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdBtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBtnSiActionPerformed

    private void RdBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBtnNoActionPerformed

    private void cboRutConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutConductorActionPerformed
        try {
            String rut=cboRutConductor.getSelectedItem().toString();
            Conductor pers= new DaoConductor().Buscar(rut);
            txtNombreConductor.setText(pers.getNombre());
            lblIdConductor.setText(""+pers.getIdConductor());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboRutConductorActionPerformed

    private void cboRutUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutUsuarioActionPerformed
        try {
            String rut=cboRutUsuario.getSelectedItem().toString();
            Usuario pers= new DaoUsuario().Buscar(rut);
            txtNombreUsuario.setText(pers.getNombre());
            lblIdCliente.setText(""+pers.getIdCliente());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboRutUsuarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int fila=JTblListarViajes.getSelectedRow();
        int idViaje=Integer.parseInt(JTblListarViajes.getValueAt(fila, 0).toString());
        Viaje via = new DaoViaje().Buscar2(idViaje);
        if (via != null) {
            JOptionPane.showMessageDialog(null, "Existe Viaje ");
            txtIdViaje.setText(""+via.getId_viaje());
            cboRutConductor.setSelectedItem(via.getConductor().getRut());
            cboRutUsuario.setSelectedItem(via.getUsuario().getRut());
            cboVehiculo.setSelectedItem(via.getVehiculo().getChasisVehiculo());
            txtDireccionInicio.setText(via.getDireccionInicio());
            txtDireccionDestino.setText(via.getDireccionDestino());
            lblVehiculo.setText(""+via.getVehiculo().getIdVehiculo());
            lblIdConductor.setText(""+via.getConductor().getIdConductor());
            lblIdCliente.setText(""+via.getUsuario().getIdCliente());
            

            if (via.isIdaYVuelta()==true){
                RdBtnSi.setSelected(true);
            }else{
                RdBtnSi.setSelected(false);
            }
            JdcFechaDeViaje.setDate(via.getFechaDeViaje());
        } else {
            JOptionPane.showMessageDialog(null, "No Existe Viaje");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        JfrmMenu menu =new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtIdViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdViajeActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int idViaje = Integer.parseInt(txtIdViaje.getText());
        
        String conductor= cboRutConductor.getSelectedItem().toString();
        int idConductor = Integer.parseInt(lblIdConductor.getText());
        Conductor c = new Conductor();
        c.setRut(conductor);
        c.setIdConductor(idConductor);
        
        String usuario = cboRutUsuario.getSelectedItem().toString();
        int idUsuario = Integer.parseInt(lblIdCliente.getText());
        Usuario u = new Usuario();
        u.setRut(usuario);
        u.setIdCliente(idUsuario);
        
        String vehiculo= cboVehiculo.getSelectedItem().toString();
        int idVehiculo = Integer.parseInt(lblVehiculo.getText());
        Vehiculo v = new Vehiculo();
        v.setChasisVehiculo(vehiculo);
        v.setIdVehiculo(idVehiculo);
        
        String DireccionInicio= txtDireccionInicio.getText();
        String DireccionDestino= txtDireccionDestino.getText();
        boolean IdaYVuelta;
        if (RdBtnSi.isSelected()){
            IdaYVuelta=true;
        }else{
            IdaYVuelta=false;
        }
        java.util.Date FechaDeViaje = JdcFechaDeViaje.getDate();
        try {
            ////////////////////////////////////////////////////////
            Viaje via = new Viaje(idViaje, c, u, v, DireccionInicio, DireccionDestino, IdaYVuelta, FechaDeViaje);
            ////////////////////////////////////////////////////////
            boolean resp = new DaoViaje().Grabar(via);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
            }
        Listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error btn guardar: "+e.getMessage());
        } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnFiltrarPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarPatenteActionPerformed
        ListarFiltroPatente();
    }//GEN-LAST:event_btnFiltrarPatenteActionPerformed

    private void btnListarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFechaActionPerformed
        Listar();
    }//GEN-LAST:event_btnListarFechaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila=JTblListarViajes.getSelectedRow();
        int id_Viaje=Integer.parseInt(JTblListarViajes.getValueAt(fila, 0).toString());
        DaoViaje via = new DaoViaje();
        boolean resp = via.Eliminar(id_Viaje);
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Elimino");
            Listar();
        } else {
            JOptionPane.showMessageDialog(null, "No Elimino");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int idViaje = Integer.parseInt(txtIdViaje.getText());
        
        String conductor= cboRutConductor.getSelectedItem().toString();
        int idConductor = Integer.parseInt(lblIdConductor.getText());
        Conductor c = new Conductor();
        c.setRut(conductor);
        c.setIdConductor(idConductor);
        
        String usuario = cboRutUsuario.getSelectedItem().toString();
        int idUsuario = Integer.parseInt(lblIdCliente.getText());
        Usuario u = new Usuario();
        u.setRut(usuario);
        u.setIdCliente(idUsuario);
        
        String vehiculo= cboVehiculo.getSelectedItem().toString();
        int idVehiculo = Integer.parseInt(lblVehiculo.getText());
        Vehiculo v = new Vehiculo();
        v.setChasisVehiculo(vehiculo);
        v.setIdVehiculo(idVehiculo);
        
        String DireccionInicio= txtDireccionInicio.getText();
        String DireccionDestino= txtDireccionDestino.getText();
        boolean IdaYVuelta;
        if (RdBtnSi.isSelected()){
            IdaYVuelta=true;
        }else{
            IdaYVuelta=false;
        }
        java.util.Date FechaDeViaje = JdcFechaDeViaje.getDate();
        try {
            ////////////////////////////////////////////////////////
            Viaje via = new Viaje(idViaje, c, u, v, DireccionInicio, DireccionDestino, IdaYVuelta, FechaDeViaje);
            ////////////////////////////////////////////////////////

            DaoViaje dao = new DaoViaje();
            boolean resp = dao.modificar(via);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modificó");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Modificó");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVehiculoActionPerformed
        try {
            String chasis=cboVehiculo.getSelectedItem().toString();
            Vehiculo veh= new DaoVehiculo().Buscar(chasis);
            lblVehiculo.setText(""+veh.getIdVehiculo());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboVehiculoActionPerformed

    private void mnuVolverMenuViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVolverMenuViajeActionPerformed
        JfrmMenu menu =new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuVolverMenuViajeActionPerformed

    private void mnuCerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuCerrarProgramaActionPerformed

    private void CerrarSesionViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionViajeActionPerformed
        JfrmLogin login =new JfrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionViajeActionPerformed

    private void JTblListarViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblListarViajesMouseClicked
        int fila=JTblListarViajes.getSelectedRow();
        int idViaje=Integer.parseInt(JTblListarViajes.getValueAt(fila, 0).toString());
        Viaje via = new DaoViaje().Buscar2(idViaje);
        if (via != null) {
            txtIdViaje.setText(""+via.getId_viaje());
            cboRutConductor.setSelectedItem(via.getConductor().getRut());
            cboRutUsuario.setSelectedItem(via.getUsuario().getRut());
            cboVehiculo.setSelectedItem(via.getVehiculo().getChasisVehiculo());
            txtDireccionInicio.setText(via.getDireccionInicio());
            txtDireccionDestino.setText(via.getDireccionDestino());
            lblVehiculo.setText(""+via.getVehiculo().getIdVehiculo());
            lblIdConductor.setText(""+via.getConductor().getIdConductor());
            lblIdCliente.setText(""+via.getUsuario().getIdCliente());
            

            if (via.isIdaYVuelta()==true){
                RdBtnSi.setSelected(true);
            }else{
                RdBtnSi.setSelected(false);
            }
            JdcFechaDeViaje.setDate(via.getFechaDeViaje());
        } else {
            JOptionPane.showMessageDialog(null, "No Existe Viaje");
        }
    }//GEN-LAST:event_JTblListarViajesMouseClicked

    private void JTblListarViajesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTblListarViajesKeyTyped
//        int fila=JTblListarViajes.getSelectedRow();
//        int idViaje=Integer.parseInt(JTblListarViajes.getValueAt(fila, 0).toString());
//        Viaje via = new DaoViaje().Buscar2(idViaje);
//        if (via != null) {
//            txtIdViaje.setText(""+via.getId_viaje());
//            cboRutConductor.setSelectedItem(via.getConductor().getRut());
//            cboRutUsuario.setSelectedItem(via.getUsuario().getRut());
//            cboVehiculo.setSelectedItem(via.getVehiculo().getChasisVehiculo());
//            txtDireccionInicio.setText(via.getDireccionInicio());
//            txtDireccionDestino.setText(via.getDireccionDestino());
//            lblVehiculo.setText(""+via.getVehiculo().getIdVehiculo());
//            lblIdConductor.setText(""+via.getConductor().getIdConductor());
//            lblIdCliente.setText(""+via.getUsuario().getIdCliente());
//            
//
//            if (via.isIdaYVuelta()==true){
//                RdBtnSi.setSelected(true);
//            }else{
//                RdBtnSi.setSelected(false);
//            }
//            JdcFechaDeViaje.setDate(via.getFechaDeViaje());
//        } else {
//            JOptionPane.showMessageDialog(null, "No Existe Viaje");
//        }
    }//GEN-LAST:event_JTblListarViajesKeyTyped


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrmViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesionViaje;
    private javax.swing.JTable JTblListarViajes;
    private com.toedter.calendar.JDateChooser JdcFechaDeViaje;
    private javax.swing.JRadioButton RdBtnNo;
    private javax.swing.JRadioButton RdBtnSi;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrarPatente;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListarFecha;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboFiltroPatente;
    private javax.swing.JComboBox<String> cboRutConductor;
    private javax.swing.JComboBox<String> cboRutUsuario;
    private javax.swing.JComboBox<String> cboVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdConductor;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JMenuItem mnuCerrarPrograma;
    private javax.swing.JMenuItem mnuVolverMenuViaje;
    private javax.swing.JTextField txtDireccionDestino;
    private javax.swing.JTextField txtDireccionInicio;
    private javax.swing.JTextField txtIdViaje;
    private javax.swing.JTextField txtNombreConductor;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

}
