package Vista;


import Controlador.DaoVehiculo;
import Enumeradores.EnumMarca;
import Enumeradores.EnumModelo;
import Modelo.Vehiculo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JFrmVehiculo extends javax.swing.JFrame {

    public JFrmVehiculo() {
        initComponents();
        Limpiar();
        Listar();
        ListarCbo();
        setLocationRelativeTo(null);
    }

    private void Limpiar(){
        txtChasisVehiculo.setText("");
        txtPatenteVehiculo.setText("");
    
    }

    private void Listar() {
        DefaultTableModel modelo=new DefaultTableModel();
        JTblListarAutos.setModel(modelo);
        modelo.addColumn("Chasis");
        modelo.addColumn("Patente");
        modelo.addColumn("Año");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        ArrayList<Vehiculo> listado=new DaoVehiculo().Listar();
        for (Vehiculo item : listado) {
            Object[] fila=new Object[5];
            fila[0]=item.getChasisVehiculo();
            fila[1]=item.getPatenteVehiculo();
            fila[2]=item.getAnoFabricacion();
            fila[3]=item.getMarcaVehiculo();
            fila[4]=item.getModeloVehiculo();
            modelo.addRow(fila);
        }
    }
    
    private void ListarCbo(){
        
        cboMarcaVehiculo.setModel(new DefaultComboBoxModel(EnumMarca.values()));
        cboModeloVehiculo.setModel(new DefaultComboBoxModel(EnumModelo.values()));
    
    
        cboFiltroAno.addItem("Seleccione");
        ArrayList<Vehiculo> vehi= new ArrayList<>();
        DaoVehiculo rc=new DaoVehiculo();
        vehi=rc.Listar();
        for(int i=0;i<vehi.size();i++)
        {
            cboFiltroAno.addItem(""+vehi.get(i).getAnoFabricacion());
        }
    }
    
    public void ListarAno() {
        DefaultTableModel modelo = new DefaultTableModel();
        JTblListarAutos.setModel(modelo);
        modelo.addColumn("Chasis");
        modelo.addColumn("Patente");
        modelo.addColumn("Año");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        ArrayList<Vehiculo> listado=new DaoVehiculo().Listar();
        String AnoVeh = cboFiltroAno.getSelectedItem().toString();
        int An = Integer.parseInt(AnoVeh);
        for (Vehiculo item : listado) {
            if(item.getAnoFabricacion()==An){
                Object[] fila = new Object[5];
                fila[0]=item.getChasisVehiculo();
                fila[1]=item.getPatenteVehiculo();
                fila[2]=item.getAnoFabricacion();
                fila[3]=item.getMarcaVehiculo();
                fila[4]=item.getModeloVehiculo();
                modelo.addRow(fila);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblListarAutos = new javax.swing.JTable();
        cboFiltroAno = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        txtPatenteVehiculo = new javax.swing.JTextField();
        txtChasisVehiculo = new javax.swing.JTextField();
        spnAnoFabricacion = new javax.swing.JSpinner();
        cboMarcaVehiculo = new javax.swing.JComboBox<>();
        cboModeloVehiculo = new javax.swing.JComboBox<>();
        btnVover = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdVehiculo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVolver = new javax.swing.JMenu();
        mnuVolverMenu = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administar Vehiculo");
        setMinimumSize(new java.awt.Dimension(691, 480));
        setResizable(false);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Chasis Vehiculo");

        jLabel2.setText("Patente Vehiculo");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Año Fabricacion");

        JTblListarAutos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JTblListarAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTblListarAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblListarAutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblListarAutos);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtPatenteVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatenteVehiculoActionPerformed(evt);
            }
        });

        txtChasisVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChasisVehiculoActionPerformed(evt);
            }
        });

        spnAnoFabricacion.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2030, 1));

        cboMarcaVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboModeloVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVover.setText("Volver");
        btnVover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoverActionPerformed(evt);
            }
        });

        jLabel6.setText("id Vehiculo");

        txtIdVehiculo.setEditable(false);
        txtIdVehiculo.setText("00");
        txtIdVehiculo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdVehiculo.setEnabled(false);
        txtIdVehiculo.setMaximumSize(new java.awt.Dimension(64, 22));
        txtIdVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVehiculoActionPerformed(evt);
            }
        });

        mnuVolver.setText("Inicio");

        mnuVolverMenu.setText("Volver al Menu");
        mnuVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVolverMenuActionPerformed(evt);
            }
        });
        mnuVolver.add(mnuVolverMenu);

        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuVolver.add(mnuCerrarSesion);
        mnuVolver.add(jSeparator1);

        mnuSalir.setText("Cerrar Programa");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuVolver.add(mnuSalir);

        jMenuBar1.add(mnuVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(txtPatenteVehiculo)
                            .addComponent(txtChasisVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(spnAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMarcaVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboModeloVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboFiltroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVover))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFiltroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar)
                    .addComponent(btnFiltrar)
                    .addComponent(btnVover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChasisVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(txtPatenteVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAnoFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnGuardar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatenteVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatenteVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteVehiculoActionPerformed

    private void txtChasisVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChasisVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChasisVehiculoActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        ListarAno();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int fila=JTblListarAutos.getSelectedRow();
        String chasis = JTblListarAutos.getValueAt(fila, 0).toString();
        Vehiculo vehi = new DaoVehiculo().Buscar(chasis);
        if (vehi != null) {    
            txtIdVehiculo.setText(""+vehi.getIdVehiculo());
            txtChasisVehiculo.setText(vehi.getChasisVehiculo());          
            txtPatenteVehiculo.setText(vehi.getPatenteVehiculo());          
            spnAnoFabricacion.setValue(vehi.getAnoFabricacion());
            cboMarcaVehiculo.setSelectedItem(EnumMarca.valueOf(vehi.getMarcaVehiculo()));
            cboModeloVehiculo.setSelectedItem(EnumModelo.valueOf(vehi.getModeloVehiculo()));
        } else {
            JOptionPane.showMessageDialog(null, "No Existe Vehiculo");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoverActionPerformed
        JfrmMenu menu= new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int idVehiculo = Integer.parseInt(txtIdVehiculo.getText());
        String chasisVehiculo = txtChasisVehiculo.getText();
        String patenteVehiculo= txtPatenteVehiculo.getText();
        int AnoFabricacion = Integer.parseInt(spnAnoFabricacion.getValue().toString());
        String marcaVehiculo= cboMarcaVehiculo.getSelectedItem().toString();
        String modeloVehiculo= cboModeloVehiculo.getSelectedItem().toString();

        try {
            ////////////////////////////////////////////////////////
            Vehiculo vehi = new Vehiculo(idVehiculo, chasisVehiculo, patenteVehiculo, AnoFabricacion, marcaVehiculo, modeloVehiculo);
            ////////////////////////////////////////////////////////
            boolean resp = new DaoVehiculo().Grabar(vehi);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error jfrm: "+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        int idVehiculo = Integer.parseInt(txtIdVehiculo.getText());
        String ChasisVehiculo = txtChasisVehiculo.getText();
        String PatenteVehiculo= txtPatenteVehiculo.getText();
        int AnoFabricacion = Integer.parseInt(spnAnoFabricacion.getValue().toString());
        String MarcaVehiculo= cboMarcaVehiculo.getSelectedItem().toString();
        String ModeloVehiculo= cboModeloVehiculo.getSelectedItem().toString();

        try {
            ////////////////////////////////////////////////////////
            Vehiculo vehi = new Vehiculo(idVehiculo, ChasisVehiculo, PatenteVehiculo, AnoFabricacion, MarcaVehiculo, ModeloVehiculo);
            ////////////////////////////////////////////////////////

            DaoVehiculo dao = new DaoVehiculo();
            boolean resp = dao.modificar(vehi);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modificó");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Modificó");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String chasis = txtChasisVehiculo.getText();
        DaoVehiculo dao = new DaoVehiculo();
        boolean resp = dao.Eliminar(chasis);
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Elimino");
            Listar();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No Elimino");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtIdVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVehiculoActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        JfrmLogin login= new JfrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVolverMenuActionPerformed
        JfrmMenu menu= new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuVolverMenuActionPerformed

    private void JTblListarAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblListarAutosMouseClicked
        int fila=JTblListarAutos.getSelectedRow();
        String chasis = JTblListarAutos.getValueAt(fila, 0).toString();
        Vehiculo vehi = new DaoVehiculo().Buscar(chasis);
        if (vehi != null) {    
            txtIdVehiculo.setText(""+vehi.getIdVehiculo());
            txtChasisVehiculo.setText(vehi.getChasisVehiculo());          
            txtPatenteVehiculo.setText(vehi.getPatenteVehiculo());          
            spnAnoFabricacion.setValue(vehi.getAnoFabricacion());
            cboMarcaVehiculo.setSelectedItem(EnumMarca.valueOf(vehi.getMarcaVehiculo()));
            cboModeloVehiculo.setSelectedItem(EnumModelo.valueOf(vehi.getModeloVehiculo()));
        } else {
            JOptionPane.showMessageDialog(null, "No Existe Vehiculo");
        }
    }//GEN-LAST:event_JTblListarAutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTblListarAutos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVover;
    private javax.swing.JComboBox<String> cboFiltroAno;
    private javax.swing.JComboBox<String> cboMarcaVehiculo;
    private javax.swing.JComboBox<String> cboModeloVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuVolver;
    private javax.swing.JMenuItem mnuVolverMenu;
    private javax.swing.JSpinner spnAnoFabricacion;
    private javax.swing.JTextField txtChasisVehiculo;
    private javax.swing.JTextField txtIdVehiculo;
    private javax.swing.JTextField txtPatenteVehiculo;
    // End of variables declaration//GEN-END:variables
}
