
package Vista;

import Controlador.DaoProveedor;
import Controlador.DaoEmpleado;
import Controlador.DaoProductos;
import Controlador.DaoIngresoBodega;
import Modelo.Proveedor;
import Modelo.Empleado;
import Modelo.Productos;
import Modelo.IngresoBodega;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Empleado
 */
public class JFrmIngresoaBodega extends javax.swing.JFrame {

    /**
     * Creates new form JFrmUsuario
     */
    public JFrmIngresoaBodega() {
        initComponents();
        Listar();
        LlenarUsuario();
        Llenarconductor();
        LlenarVehiculo();
        LlenarVehiculoFiltro();
        Date fecha=new Date();
        JdcFechaDeIngreso.setDate(fecha);
        setLocationRelativeTo(null);
    }

    private void LlenarUsuario() {
        cboRutEmpleado.addItem("Seleccione");
        for (Empleado user : new DaoEmpleado().Listar()) {
            cboRutEmpleado.addItem(user.getRut());
            txtNombreEmpleado.setText(user.getNombre());
            
        }
    }

    private void Llenarconductor() {
        cboRutProveedor.addItem("Seleccione");
        for (Proveedor cond : new DaoProveedor().ListarConductor()) {
            cboRutProveedor.addItem(cond.getRut());
            txtNombreProveedor.setText(cond.getNombre());
            
        }
    }

    private void LlenarVehiculo() {
        cboProducto.addItem("Seleccione");
        for (Productos vehi : new DaoProductos().Listar()) {
            cboProducto.addItem(vehi.getChasisVehiculo());
            
        }
    }
    
    
    private void LlenarVehiculoFiltro() {
        cboProducto.addItem("Seleccione");
        for (Productos vehi : new DaoProductos().Listar()) {
            cboFiltroProveedor.addItem(vehi.getPatenteVehiculo());
        }
    }
    
    private void Listar() {
        DefaultTableModel modelo=new DefaultTableModel();
        JTblListarIngresos.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Conductor");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Inicio");
        modelo.addColumn("Fin");
        modelo.addColumn("IdaVuelta");
        modelo.addColumn("Fecha");
        ArrayList<IngresoBodega> listado=new DaoIngresoBodega().Listar();
        for (IngresoBodega item : listado) {
            Object[] fila=new Object[8];
            fila[0]=item.getId_viaje();
            fila[1]=item.getEmpleado().getNombre();
            fila[2]=item.getProveedor().getNombre();
            fila[3]=item.getProducto().getPatenteVehiculo();
            fila[4]=item.getDireccionInicio();
            fila[5]=item.getDireccionDestino();
            fila[6]=item.isIdaYVuelta()?"Si":"No";
            fila[7]=item.getFechaDeIngreso();
            modelo.addRow(fila);
        }
    }

    
    public void ListarFiltroPatente(){
        DefaultTableModel modelo = new DefaultTableModel();
        JTblListarIngresos.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Conductor");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Inicio");
        modelo.addColumn("Fin");
        modelo.addColumn("IdaVuelta");
        modelo.addColumn("Fecha");
        ArrayList<IngresoBodega> Listado = new DaoIngresoBodega().Listar();
        String pat = cboFiltroProveedor.getSelectedItem().toString();
        for (IngresoBodega item: Listado) {
            if(item.getProducto().getPatenteVehiculo().equals(pat)){
            Object[] fila=new Object[8];
            fila[0]=item.getId_viaje();
            fila[1]=item.getEmpleado().getNombre();
            fila[2]=item.getProveedor().getNombre();
            fila[3]=item.getProducto().getPatenteVehiculo();
            fila[4]=item.getDireccionInicio();
            fila[5]=item.getDireccionDestino();
            fila[6]=item.isIdaYVuelta()?"S":"N";
            fila[7]=item.getFechaDeIngreso().getTime();
            modelo.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionInicio = new javax.swing.JTextField();
        cboFiltroProveedor = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        txtDireccionDestino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboRutProveedor = new javax.swing.JComboBox<>();
        txtNombreProveedor = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        cboRutEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboProducto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RdBtnSi = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        RdBtnNo = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JdcFechaDeIngreso = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdViaje = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblIdConductor = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblListarIngresos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVolverMenuViaje = new javax.swing.JMenuItem();
        CerrarSesionViaje = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCerrarPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Rut Proveedor");

        jLabel2.setText("Nombre Proveedor");

        jLabel3.setText("Direccion Inicio");

        txtDireccionInicio.setMaximumSize(new java.awt.Dimension(200, 22));
        txtDireccionInicio.setMinimumSize(new java.awt.Dimension(200, 22));
        txtDireccionInicio.setPreferredSize(new java.awt.Dimension(200, 22));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtDireccionDestino.setMaximumSize(new java.awt.Dimension(200, 22));
        txtDireccionDestino.setMinimumSize(new java.awt.Dimension(200, 22));
        txtDireccionDestino.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabel6.setText("Direccion Destino");

        cboRutProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutProveedorActionPerformed(evt);
            }
        });

        txtNombreProveedor.setEditable(false);
        txtNombreProveedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreProveedor.setEnabled(false);

        txtNombreEmpleado.setEditable(false);
        txtNombreEmpleado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreEmpleado.setEnabled(false);

        cboRutEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRutEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Empleado");

        jLabel5.setText("Rut Empleado");

        cboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione Producto");

        buttonGroup1.add(RdBtnSi);
        RdBtnSi.setText("SI");
        RdBtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnSiActionPerformed(evt);
            }
        });

        jLabel8.setText("Alta Frequencia de Venta");

        buttonGroup1.add(RdBtnNo);
        RdBtnNo.setText("NO");
        RdBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnNoActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel9.setText("Filtro por Proveedor");

        jLabel10.setText("Fecha de Ingreso");

        jLabel11.setText("IdViaje");

        txtIdViaje.setEditable(false);
        txtIdViaje.setText("00");
        txtIdViaje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdViaje.setEnabled(false);
        txtIdViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdViajeActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblIdConductor.setText("00");
        lblIdConductor.setEnabled(false);

        lblIdCliente.setText("00");
        lblIdCliente.setEnabled(false);

        lblVehiculo.setText("00");
        lblVehiculo.setEnabled(false);

        JTblListarIngresos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        JTblListarIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTblListarIngresos);

        jMenu1.setText("File");

        mnuVolverMenuViaje.setText("Volver al Menu");
        mnuVolverMenuViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVolverMenuViajeActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVolverMenuViaje);

        CerrarSesionViaje.setText("Cerrar Sesion");
        CerrarSesionViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionViajeActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarSesionViaje);
        jMenu1.add(jSeparator1);

        mnuCerrarPrograma.setText("Cerrar Programa");
        mnuCerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarProgramaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCerrarPrograma);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(435, 435, 435)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel9)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboRutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RdBtnSi)
                                                .addGap(18, 18, 18)
                                                .addComponent(RdBtnNo))
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNombreProveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cboRutEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3)
                                                .addComponent(txtDireccionDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8)
                                                .addComponent(txtDireccionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JdcFechaDeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboFiltroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFiltrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnListar)))))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboFiltroProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnListar)
                                .addComponent(btnVolver)
                                .addComponent(btnFiltrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblIdConductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblIdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRutEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdBtnSi)
                            .addComponent(RdBtnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JdcFechaDeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdBtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBtnSiActionPerformed

    private void RdBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBtnNoActionPerformed

    private void cboRutProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutProveedorActionPerformed
        try {
            String rut=cboRutProveedor.getSelectedItem().toString();
            Proveedor pers= new DaoProveedor().Buscar(rut);
            txtNombreProveedor.setText(pers.getNombre());
            lblIdConductor.setText(""+pers.getIdConductor());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboRutProveedorActionPerformed

    private void cboRutEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRutEmpleadoActionPerformed
        try {
            String rut=cboRutEmpleado.getSelectedItem().toString();
            Empleado pers= new DaoEmpleado().Buscar(rut);
            txtNombreEmpleado.setText(pers.getNombre());
            lblIdCliente.setText(""+pers.getIdCliente());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboRutEmpleadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int fila=JTblListarIngresos.getSelectedRow();
        int idViaje=Integer.parseInt(JTblListarIngresos.getValueAt(fila, 0).toString());
        IngresoBodega via = new DaoIngresoBodega().Buscar2(idViaje);
        if (via != null) {
            JOptionPane.showMessageDialog(null, "Existe Viaje ");
            txtIdViaje.setText(""+via.getId_viaje());
            cboRutProveedor.setSelectedItem(via.getProveedor().getRut());
            cboRutEmpleado.setSelectedItem(via.getEmpleado().getRut());
            cboProducto.setSelectedItem(via.getProducto().getChasisVehiculo());
            txtDireccionInicio.setText(via.getDireccionInicio());
            txtDireccionDestino.setText(via.getDireccionDestino());
            lblVehiculo.setText(""+via.getProducto().getIdVehiculo());
            lblIdConductor.setText(""+via.getProveedor().getIdConductor());
            lblIdCliente.setText(""+via.getEmpleado().getIdCliente());
            

            if (via.isIdaYVuelta()==true){
                RdBtnSi.setSelected(true);
            }else{
                RdBtnSi.setSelected(false);
            }
            JdcFechaDeIngreso.setDate(via.getFechaDeIngreso());
        } else {
            JOptionPane.showMessageDialog(null, "No Existe Viaje");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        JfrmMenu menu =new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtIdViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdViajeActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int idViaje = Integer.parseInt(txtIdViaje.getText());
        
        String conductor= cboRutProveedor.getSelectedItem().toString();
        int idConductor = Integer.parseInt(lblIdConductor.getText());
        Proveedor c = new Proveedor();
        c.setRut(conductor);
        c.setIdConductor(idConductor);
        
        String usuario = cboRutEmpleado.getSelectedItem().toString();
        int idUsuario = Integer.parseInt(lblIdCliente.getText());
        Empleado u = new Empleado();
        u.setRut(usuario);
        u.setIdCliente(idUsuario);
        
        String vehiculo= cboProducto.getSelectedItem().toString();
        int idVehiculo = Integer.parseInt(lblVehiculo.getText());
        Productos v = new Productos();
        v.setChasisVehiculo(vehiculo);
        v.setIdVehiculo(idVehiculo);
        
        String DireccionInicio= txtDireccionInicio.getText();
        String DireccionDestino= txtDireccionDestino.getText();
        boolean IdaYVuelta;
        if (RdBtnSi.isSelected()){
            IdaYVuelta=true;
        }else{
            IdaYVuelta=false;
        }
        java.util.Date FechaDeViaje = JdcFechaDeIngreso.getDate();
        try {
            ////////////////////////////////////////////////////////
            IngresoBodega via = new IngresoBodega(idViaje, c, u, v, DireccionInicio, DireccionDestino, IdaYVuelta, FechaDeViaje);
            ////////////////////////////////////////////////////////
            boolean resp = new DaoIngresoBodega().Grabar(via);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
            }
        Listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error btn guardar: "+e.getMessage());
        } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        ListarFiltroPatente();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila=JTblListarIngresos.getSelectedRow();
        int id_Viaje=Integer.parseInt(JTblListarIngresos.getValueAt(fila, 0).toString());
        DaoIngresoBodega via = new DaoIngresoBodega();
        boolean resp = via.Eliminar(id_Viaje);
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Elimino");
            Listar();
        } else {
            JOptionPane.showMessageDialog(null, "No Elimino");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int idViaje = Integer.parseInt(txtIdViaje.getText());
        
        String conductor= cboRutProveedor.getSelectedItem().toString();
        int idConductor = Integer.parseInt(lblIdConductor.getText());
        Proveedor c = new Proveedor();
        c.setRut(conductor);
        c.setIdConductor(idConductor);
        
        String usuario = cboRutEmpleado.getSelectedItem().toString();
        int idUsuario = Integer.parseInt(lblIdCliente.getText());
        Empleado u = new Empleado();
        u.setRut(usuario);
        u.setIdCliente(idUsuario);
        
        String vehiculo= cboProducto.getSelectedItem().toString();
        int idVehiculo = Integer.parseInt(lblVehiculo.getText());
        Productos v = new Productos();
        v.setChasisVehiculo(vehiculo);
        v.setIdVehiculo(idVehiculo);
        
        String DireccionInicio= txtDireccionInicio.getText();
        String DireccionDestino= txtDireccionDestino.getText();
        boolean IdaYVuelta;
        if (RdBtnSi.isSelected()){
            IdaYVuelta=true;
        }else{
            IdaYVuelta=false;
        }
        java.util.Date FechaDeViaje = JdcFechaDeIngreso.getDate();
        try {
            ////////////////////////////////////////////////////////
            IngresoBodega via = new IngresoBodega(idViaje, c, u, v, DireccionInicio, DireccionDestino, IdaYVuelta, FechaDeViaje);
            ////////////////////////////////////////////////////////

            DaoIngresoBodega dao = new DaoIngresoBodega();
            boolean resp = dao.modificar(via);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modificó");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Modificó");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductoActionPerformed
        try {
            String chasis=cboProducto.getSelectedItem().toString();
            Productos veh= new DaoProductos().Buscar(chasis);
            lblVehiculo.setText(""+veh.getIdVehiculo());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboProductoActionPerformed

    private void mnuVolverMenuViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVolverMenuViajeActionPerformed
        JfrmMenu menu =new JfrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuVolverMenuViajeActionPerformed

    private void mnuCerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuCerrarProgramaActionPerformed

    private void CerrarSesionViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionViajeActionPerformed
        JfrmLogin login =new JfrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionViajeActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresoaBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresoaBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresoaBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresoaBodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrmIngresoaBodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesionViaje;
    private javax.swing.JTable JTblListarIngresos;
    private com.toedter.calendar.JDateChooser JdcFechaDeIngreso;
    private javax.swing.JRadioButton RdBtnNo;
    private javax.swing.JRadioButton RdBtnSi;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboFiltroProveedor;
    private javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JComboBox<String> cboRutEmpleado;
    private javax.swing.JComboBox<String> cboRutProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdConductor;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JMenuItem mnuCerrarPrograma;
    private javax.swing.JMenuItem mnuVolverMenuViaje;
    private javax.swing.JTextField txtDireccionDestino;
    private javax.swing.JTextField txtDireccionInicio;
    private javax.swing.JTextField txtIdViaje;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNombreProveedor;
    // End of variables declaration//GEN-END:variables

}
