package Vista;

import Modelo.Doctor;
import Modelo.Especialidad;
import controlador.DaoDoctor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JFrmAdminDoctor extends javax.swing.JFrame {

    public JFrmAdminDoctor() {
        initComponents();
        ListarCbo();
        Listar();
        this.setLocationRelativeTo(null);
    }
    
    public void ListarCbo(){
        cboEspecialidad.addItem("Seleccione");
        ArrayList<Especialidad> e= new ArrayList<>();
        DaoDoctor rg=new DaoDoctor();
        e=rg.ListarEspecialidad();
        for(int i=0;i<e.size();i++)
        {
          cboEspecialidad.addItem(e.get(i).getDescripcion());
        }
    }

    public void ListarEspecialidad() {
        DefaultTableModel modelo = new DefaultTableModel();
        JTblListaDoctor.setModel(modelo);
        modelo.addColumn("Id Doctor");
        modelo.addColumn("Rut Doctor");
        modelo.addColumn("Nombre Doctor");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Celular Doctor");
        modelo.addColumn("Direccion Doctor");
        modelo.addColumn("Sueldo Doctor");
        ArrayList<Doctor> Listado = new DaoDoctor().Listar();
        String EspDoc = cboEspecialidad.getSelectedItem().toString();
        for (Doctor doctor : Listado) {
            if(doctor.getEspecialidad().equals(EspDoc)){
                Object[] fila = new Object[7];
                fila[0] = doctor.getId_doctor();
                fila[1] = doctor.getNum_rut();
                fila[2] = doctor.getNombre();
                fila[3] = doctor.getEspecialidad();
                fila[4] = doctor.getCelular();
                fila[5] = doctor.getDireccion();
                fila[6] = doctor.getSueldo();
                modelo.addRow(fila);
            }
        }
    }
    
    
    
    

    public void Listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        JTblListaDoctor.setModel(modelo);
        modelo.addColumn("Id Doctor");
        modelo.addColumn("Rut Doctor");
        modelo.addColumn("Nombre Doctor");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Celular Doctor");
        modelo.addColumn("Direccion Doctor");
        modelo.addColumn("Sueldo Doctor");
        ArrayList<Doctor> Listado = new DaoDoctor().Listar();
        for (Doctor doctor : Listado) {
            Object[] fila = new Object[7];
            fila[0] = doctor.getId_doctor();
            fila[1] = doctor.getNum_rut();
            fila[2] = doctor.getNombre();
            fila[3] = doctor.getEspecialidad();
            fila[4] = doctor.getCelular();
            fila[5] = doctor.getDireccion();
            fila[6] = doctor.getSueldo();
            modelo.addRow(fila);
        }

    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnGrabarDoctor = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnBuscarDoctor = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        txtRutDoctor = new javax.swing.JTextField();
        txtDireccionDoctor = new javax.swing.JTextField();
        txtSueldoDoctor = new javax.swing.JTextField();
        txtNombreDoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEspecialidadDoctor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCelularDoctor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdDoctor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboEspecialidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblListaDoctor = new javax.swing.JTable();
        BtnFiltro = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMINISTRAR DOCTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Counter-Strike", 0, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel2.setText("Rut del Doctor");

        jLabel3.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel3.setText("Direccion del Doctor");

        jLabel4.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel4.setText("Sueldo Doctor");

        BtnGrabarDoctor.setText("Grabar");
        BtnGrabarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarDoctorActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnBuscarDoctor.setText("Buscar");
        BtnBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarDoctorActionPerformed(evt);
            }
        });

        BtnBorrar.setText("Eliminar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        txtRutDoctor.setMaximumSize(new java.awt.Dimension(200, 22));
        txtRutDoctor.setMinimumSize(new java.awt.Dimension(200, 22));
        txtRutDoctor.setPreferredSize(new java.awt.Dimension(200, 22));

        txtDireccionDoctor.setMaximumSize(new java.awt.Dimension(600, 30));
        txtDireccionDoctor.setMinimumSize(new java.awt.Dimension(600, 30));
        txtDireccionDoctor.setPreferredSize(new java.awt.Dimension(600, 30));
        txtDireccionDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionDoctorActionPerformed(evt);
            }
        });

        txtSueldoDoctor.setMaximumSize(new java.awt.Dimension(600, 30));
        txtSueldoDoctor.setMinimumSize(new java.awt.Dimension(600, 30));
        txtSueldoDoctor.setPreferredSize(new java.awt.Dimension(600, 30));

        txtNombreDoctor.setMaximumSize(new java.awt.Dimension(300, 30));
        txtNombreDoctor.setMinimumSize(new java.awt.Dimension(300, 30));
        txtNombreDoctor.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel6.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel6.setText("Nombre del Doctor");

        txtEspecialidadDoctor.setMaximumSize(new java.awt.Dimension(300, 30));
        txtEspecialidadDoctor.setMinimumSize(new java.awt.Dimension(300, 30));
        txtEspecialidadDoctor.setPreferredSize(new java.awt.Dimension(300, 30));
        txtEspecialidadDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadDoctorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel7.setText("Especialidad Doctor");

        txtCelularDoctor.setMaximumSize(new java.awt.Dimension(300, 30));
        txtCelularDoctor.setMinimumSize(new java.awt.Dimension(300, 30));
        txtCelularDoctor.setPreferredSize(new java.awt.Dimension(300, 30));
        txtCelularDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularDoctorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel8.setText("Celular Doctor");

        txtIdDoctor.setText("0");
        txtIdDoctor.setMaximumSize(new java.awt.Dimension(100, 30));
        txtIdDoctor.setMinimumSize(new java.awt.Dimension(100, 30));
        txtIdDoctor.setPreferredSize(new java.awt.Dimension(100, 30));
        txtIdDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDoctorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel9.setText("ID Doctor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGrabarDoctor)
                .addGap(12, 12, 12)
                .addComponent(BtnBuscarDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBorrar)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccionDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtSueldoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel6)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel7)
                                .addGap(136, 136, 136)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRutDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEspecialidadDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCelularDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEspecialidadDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCelularDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRutDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSueldoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGrabarDoctor)
                    .addComponent(BtnModificar)
                    .addComponent(BtnBuscarDoctor)
                    .addComponent(BtnBorrar)))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado Doctores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Counter-Strike", 0, 24))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1366, 768));

        cboEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEspecialidadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Counter-Strike", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione Especialidad");

        JTblListaDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTblListaDoctor);

        BtnFiltro.setText("Aplicar Filtro");
        BtnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltroActionPerformed(evt);
            }
        });

        BtnListar.setText("Listar Todo");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });

        BtnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnListar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnFiltro)
                    .addComponent(BtnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jMenu1.setText("INICIO");

        mnuVolver.setText("Volver");
        mnuVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVolverActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVolver);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVolverActionPerformed
        JFrmMainMenu mainmenu=new JFrmMainMenu();
        mainmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuVolverActionPerformed

    private void BtnGrabarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarDoctorActionPerformed
        
        int id_doctor = Integer.parseInt(txtIdDoctor.getText());
        int num_rut = Integer.parseInt(txtRutDoctor.getText());
        int celular = Integer.parseInt(txtCelularDoctor.getText());
        int sueldo = Integer.parseInt(txtSueldoDoctor.getText());
        String especialidad = txtEspecialidadDoctor.getText();
        String nombre = txtNombreDoctor.getText();
        String direccion = txtDireccionDoctor.getText();
        
        
        
        
        try {
            ////////////////////////////////////////////////////////
            Doctor doc = new Doctor(id_doctor,especialidad, sueldo, nombre, num_rut, direccion, celular);
            ////////////////////////////////////////////////////////

            DaoDoctor dao = new DaoDoctor();
            boolean resp = dao.Grabar(doc);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_BtnGrabarDoctorActionPerformed

    private void txtDireccionDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionDoctorActionPerformed

    private void BtnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltroActionPerformed
        ListarEspecialidad();
    }//GEN-LAST:event_BtnFiltroActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        Listar();
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        JFrmMainMenu mainmenu=new JFrmMainMenu();
        mainmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void txtEspecialidadDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadDoctorActionPerformed

    private void txtCelularDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularDoctorActionPerformed

    private void BtnBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarDoctorActionPerformed
        int id_doctor = Integer.parseInt(txtIdDoctor.getText());
        Doctor doc = new DaoDoctor().Buscar(id_doctor);
        if (doc != null) {
            JOptionPane.showMessageDialog(null, "Existe Doctor");
            txtIdDoctor.setText(String.valueOf(doc.getId_doctor()));
            txtRutDoctor.setText(String.valueOf(doc.getNum_rut()));
            txtNombreDoctor.setText("" + doc.getNombre());
            txtEspecialidadDoctor.setText("" + doc.getEspecialidad());
            txtCelularDoctor.setText("" + doc.getCelular());
            txtDireccionDoctor.setText("" + doc.getDireccion());
            txtSueldoDoctor.setText("" + doc.getSueldo());

        } else {
            JOptionPane.showMessageDialog(null, "No Existe Doctor");
        }
    }//GEN-LAST:event_BtnBuscarDoctorActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        int id_doctor = Integer.parseInt(txtIdDoctor.getText());
        DaoDoctor dao = new DaoDoctor();
        boolean resp = dao.Eliminar(id_doctor);
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Elimino");
            Listar();
        } else {
            JOptionPane.showMessageDialog(null, "No Elimino");
        }
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void cboEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEspecialidadActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        int id_doctor = Integer.parseInt(txtIdDoctor.getText());
        int num_rut = Integer.parseInt(txtRutDoctor.getText());
        int celular = Integer.parseInt(txtCelularDoctor.getText());
        int sueldo = Integer.parseInt(txtSueldoDoctor.getText());
        String nombre = txtNombreDoctor.getText();
        String direccion = txtDireccionDoctor.getText();
        String especialidad = txtEspecialidadDoctor.getText();

        try {
            ////////////////////////////////////////////////////////
            Doctor doc = new Doctor(id_doctor,especialidad, sueldo, nombre, num_rut, direccion, celular);
            ////////////////////////////////////////////////////////

            DaoDoctor dao = new DaoDoctor();
            boolean resp = dao.Modificar(doc);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modifico");
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Modifico");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void txtIdDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAdminDoctor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAdminDoctor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAdminDoctor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAdminDoctor.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAdminDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBuscarDoctor;
    private javax.swing.JButton BtnFiltro;
    private javax.swing.JButton BtnGrabarDoctor;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable JTblListaDoctor;
    private javax.swing.JComboBox<String> cboEspecialidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuVolver;
    private javax.swing.JTextField txtCelularDoctor;
    private javax.swing.JTextField txtDireccionDoctor;
    private javax.swing.JTextField txtEspecialidadDoctor;
    private javax.swing.JTextField txtIdDoctor;
    private javax.swing.JTextField txtNombreDoctor;
    private javax.swing.JTextField txtRutDoctor;
    private javax.swing.JTextField txtSueldoDoctor;
    // End of variables declaration//GEN-END:variables
}
